export const items = [
  {
    itemName: "Engine Oil",
    category: "Fluids",
    manufacturer: "Mobil",
    reorderLevel: 20,
    pricePerUnit: 5.99,
    description: "High-quality synthetic engine oil",
  },
  {
    itemName: "Brake Pads",
    category: "Brakes",
    manufacturer: "Bosch",
    reorderLevel: 15,
    pricePerUnit: 25.5,
    description: "Ceramic brake pads for superior stopping power",
  },
  {
    itemName: "Air Filter",
    category: "Filters",
    manufacturer: "Fram",
    reorderLevel: 30,
    pricePerUnit: 8.75,
    description: "Air filter for improved engine performance",
  },
  {
    itemName: "Spark Plugs",
    category: "Ignition",
    manufacturer: "NGK",
    reorderLevel: 25,
    pricePerUnit: 2.5,
    description: "Platinum spark plugs for efficient ignition",
  },
  {
    itemName: "Wiper Blades",
    category: "Accessories",
    manufacturer: "Rain-X",
    reorderLevel: 10,
    pricePerUnit: 12.99,
    description: "High-performance wiper blades",
  },
  {
    itemName: "Transmission Fluid",
    category: "Fluids",
    manufacturer: "Valvoline",
    reorderLevel: 15,
    pricePerUnit: 9.75,
    description: "Automatic transmission fluid",
  },
  {
    itemName: "Radiator",
    category: "Cooling",
    manufacturer: "AC Delco",
    reorderLevel: 5,
    pricePerUnit: 65.0,
    description: "Aluminum radiator for effective cooling",
  },
  {
    itemName: "Battery",
    category: "Electrical",
    manufacturer: "Optima",
    reorderLevel: 8,
    pricePerUnit: 150.0,
    description: "Maintenance-free car battery",
  },
  {
    itemName: "Tire Pressure Gauge",
    category: "Accessories",
    manufacturer: "Michelin",
    reorderLevel: 12,
    pricePerUnit: 9.99,
    description: "Digital tire pressure gauge",
  },
  {
    itemName: "Jack Stands",
    category: "Tools",
    manufacturer: "Craftsman",
    reorderLevel: 5,
    pricePerUnit: 32.5,
    description: "Heavy-duty jack stands for lifting",
  },
  {
    itemName: "Brake Rotors",
    category: "Brakes",
    manufacturer: "Brembo",
    reorderLevel: 10,
    pricePerUnit: 45.75,
    description: "Performance brake rotors",
  },
  {
    itemName: "Cabin Air Filter",
    category: "Filters",
    manufacturer: "Purolator",
    reorderLevel: 20,
    pricePerUnit: 12.25,
    description: "Filter for clean air in the cabin",
  },
  {
    itemName: "Oxygen Sensor",
    category: "Sensors",
    manufacturer: "Bosch",
    reorderLevel: 15,
    pricePerUnit: 28.5,
    description: "Measures oxygen levels in exhaust gases",
  },
  {
    itemName: "Serpentine Belt",
    category: "Belts",
    manufacturer: "Gates",
    reorderLevel: 25,
    pricePerUnit: 15.99,
    description: "Drives multiple engine accessories",
  },
  {
    itemName: "Fuel Pump",
    category: "Fuel System",
    manufacturer: "ACDelco",
    reorderLevel: 8,
    pricePerUnit: 65.0,
    description: "Delivers fuel from tank to engine",
  },
  {
    itemName: "Thermostat",
    category: "Cooling",
    manufacturer: "Stant",
    reorderLevel: 12,
    pricePerUnit: 7.99,
    description: "Regulates engine temperature",
  },
  {
    itemName: "Power Steering Fluid",
    category: "Fluids",
    manufacturer: "Prestone",
    reorderLevel: 10,
    pricePerUnit: 6.5,
    description: "Fluid for power steering system",
  },
  {
    itemName: "Shock Absorbers",
    category: "Suspension",
    manufacturer: "KYB",
    reorderLevel: 10,
    pricePerUnit: 32.0,
    description: "Absorbs shocks from road bumps",
  },
  {
    itemName: "Ignition Coil",
    category: "Ignition",
    manufacturer: "Denso",
    reorderLevel: 20,
    pricePerUnit: 18.75,
    description: "Generates high voltage for spark plugs",
  },
  {
    itemName: "Alternator",
    category: "Electrical",
    manufacturer: "AC Delco",
    reorderLevel: 5,
    pricePerUnit: 120.0,
    description: "Generates electrical power for the car",
  },
];
